// ./gradlew dependencies : 의존성 확인
// ./gradlew build        : 프로젝트 빌드
// ./gradlew bootRun      : 스프링 애플리케이션 실행

plugins {
    id 'java'
    id 'org.springframework.boot' version '3.4.2'
    id 'io.spring.dependency-management' version '1.1.7'
}

group = 'com.example'
version = '0.0.1-SNAPSHOT'

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(17)
    }
}

repositories {
    mavenCentral()
}

dependencies {
    // Spring Boot
    implementation 'org.springframework.boot:spring-boot-starter-web'
    implementation 'org.springframework.boot:spring-boot-starter-data-jpa'
    implementation 'org.springframework.boot:spring-boot-starter-thymeleaf'
    implementation 'org.springframework.boot:spring-boot-starter-security'
    implementation 'org.springframework.boot:spring-boot-starter-oauth2-client'

    // WebFlux 의존성 추가 (WebClient를 사용하기 위해)
    implementation 'org.springframework.boot:spring-boot-starter-webflux'

    // Thymeleaf + Security extras
    implementation 'org.thymeleaf.extras:thymeleaf-extras-springsecurity6'

    // Lombok
    compileOnly 'org.projectlombok:lombok'
    annotationProcessor 'org.projectlombok:lombok'

    // DB Driver (MySQL)
    runtimeOnly 'com.mysql:mysql-connector-j'

    // Jackson
    implementation 'com.fasterxml.jackson.core:jackson-databind'

    // Validation
    implementation 'org.springframework.boot:spring-boot-starter-validation'

    // DevTools (Optional)
    developmentOnly 'org.springframework.boot:spring-boot-devtools'

    // Tests
    testImplementation 'org.springframework.boot:spring-boot-starter-test'
    testImplementation 'org.springframework.security:spring-security-test'
    testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
}

tasks.named('test') {
    useJUnitPlatform()
}

// Gradle을 통해 컴파일 시 파라미터 이름 정보를 보존하도록 설정
tasks.withType(JavaCompile) {
    options.compilerArgs = ['-parameters']
    options.encoding = 'UTF-8'
}
